SELECT b.NAME_OF_SCHOOL,a.COMMUNITY_AREA_NAME,b.AVERAGE_STUDENT_ATTENDANCE,a.HARDSHIP_INDEX
FROM CHICAGO_PUBLIC_SCHOOLS b left join CENSUS_DATA a on b.COMMUNITY_AREA_NUMBER=a.COMMUNITY_AREA_NUMBER
WHERE a.HARDSHIP_INDEX=98;


SELECT c.CASE_NUMBER,c.PRIMARY_TYPE, a.COMMUNITY_AREA_NAME,c.LOCATION_DESCRIPTION
FROM CHICAGO_CRIME_DATA c left JOIN CENSUS_DATA a ON a.COMMUNITY_AREA_NUMBER=c.COMMUNITY_AREA_NUMBER
WHERE c.LOCATION_DESCRIPTION like '%SCHOOL%';

CREATE VIEW QUESTION1(School_Name,Safety_Rating,Family_Rating,Environment_Rating,	Instruction_Rating,Leaders_Rating,Teachers_Rating)
AS SELECT NAME_OF_SCHOOL,Safety_Icon,Family_Involvement_Icon,Environment_Icon,Instruction_Icon,Leaders_Icon,Teachers_Icon
FROM CHICAGO_PUBLIC_SCHOOLS;

SELECT * FROM QUESTION1;

SELECT School_Name, Leaders_Rating FROM QUESTION1;


