ALTER TABLE CHICAGO_PUBLIC_SCHOOLS      
ALTER COLUMN "LEADERS_ICON"     
SET DATA TYPE VARCHAR(20); 

call UPDATE_LEADERS_SCORE(400018,50);

SELECT SCHOOL_ID,LEADERS_ICON FROM CHICAGO_PUBLIC_SCHOOLS WHERE SCHOOL_ID=400018;

DROP PROCEDURE UPDATE_LEADERS_SCORE;

call UPDATE_LEADERS_SCORE(400018,38);

SELECT SCHOOL_ID,LEADERS_ICON FROM CHICAGO_PUBLIC_SCHOOLS WHERE SCHOOL_ID=400018;

call UPDATE_LEADERS_SCORE(400018,101);

SELECT SCHOOL_ID,LEADERS_ICON FROM CHICAGO_PUBLIC_SCHOOLS WHERE SCHOOL_ID=400018;